#!/bin/sh
#
# A helper devscript to recreate Invenio demo site.  Assumes an
# already running Invenio instance on the box, and certain sudo
# rights.  For more information, see
# <https://github.com/tiborsimko/invenio-devscripts>.
#
# Tibor Simko <tibor.simko@cern.ch>
#
# Copyright (C) 2011, 2012, 2013, 2014 CERN.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

# config section:
CFG_INVENIO_SRCDIR=${CFG_INVENIO_SRCDIR:=~/private/src/invenio}
CFG_INVENIO_PREFIX=${CFG_INVENIO_PREFIX:=/opt/invenio}
CFG_INVENIO_HOSTNAME=${CFG_INVENIO_HOSTNAME:=pcuds06}
CFG_INVENIO_DOMAINNAME=${CFG_INVENIO_DOMAINNAME:=cern.ch}
CFG_INVENIO_PORT_HTTP=${CFG_INVENIO_PORT_HTTP:=80}
CFG_INVENIO_PORT_HTTPS=${CFG_INVENIO_PORT_HTTPS:=443}
CFG_INVENIO_USER=${CFG_INVENIO_USER:=www-data}
CFG_INVENIO_ADMIN=${CFG_INVENIO_ADMIN:=tibor.simko@cern.ch}
CFG_INVENIO_DATABASE_NAME=${CFG_INVENIO_DATABASE_NAME:=invenio}
CFG_INVENIO_DATABASE_USER=${CFG_INVENIO_DATABASE_USER:=invenio}
CFG_INVENIO_DATABASE_PASS=${CFG_INVENIO_DATABASE_PASS:=my123p\$ss}
CFG_INVENIO_APACHECTL=${CFG_INVENIO_APACHECTL:=/etc/init.d/apache2}
CFG_INVENIO_MYSQLCTL=${CFG_INVENIO_MYSQLCTL:=/etc/init.d/mysql}
CFG_INVENIO_SYMLINK_INSTALLER=${CFG_INVENIO_SYMLINK_INSTALLER:=0}
CFG_INVENIO_SITE_LANGS=${CFG_INVENIO_SITE_LANGS:=all}

# sanity check: CLI confirmation
if [ "$1" != "--yes-i-know" ]; then
    echo "[ERROR] You did not use --yes-i-know.  Not going to recreate Invenio demo site."
    exit
fi

# quit on errors and potentially unbound symbols:
set -o errexit
set -o nounset

# sanity check: hostname
if [ "`hostname -s`" != "$CFG_INVENIO_HOSTNAME" ]; then
    echo "[ERROR] This hostname is not whitelisted for recreating the demo site."
    exit
fi

# give user a chance to quit:
echo "[INFO] GOING TO RECREATE YOUR INVENIO DEMO SITE IN 5 SECONDS!"
echo -n "[INFO] THIS IS YOUR LAST CHANCE TO INTERRUPT BY PRESSING Ctrl-C! "
for i in 0 1 2 3 4; do
    echo -n "."
    sleep 1
done
echo

# wipe out existing installation place:
sudo rm -rf $CFG_INVENIO_PREFIX/var/tmp/ooffice-tmp-files
sudo -u $CFG_INVENIO_USER rm -rf $CFG_INVENIO_PREFIX/*

# install Invenio sources:
cd $CFG_INVENIO_SRCDIR
rm -rf autom4te.cache/
aclocal
automake -a
autoconf
if [ "${CFG_INVENIO_SYMLINK_INSTALLER}" = "1" ]; then
    INSTALL=`which invenio-symlink-installer` ./configure --prefix=$CFG_INVENIO_PREFIX
else
    ./configure --prefix=$CFG_INVENIO_PREFIX
fi
make -s
sudo -u $CFG_INVENIO_USER make -s install
sudo -u $CFG_INVENIO_USER make -s install-jquery-plugins
sudo -u $CFG_INVENIO_USER make -s install-mathjax-plugin
sudo -u $CFG_INVENIO_USER make -s install-ckeditor-plugin
sudo -u $CFG_INVENIO_USER make -s install-pdfa-helper-files

# if applicable, install also Twitter Bootstrap (for 'next' branch):
if grep -q install-bootstrap INSTALL; then
    sudo -u $CFG_INVENIO_USER make -s install-bootstrap
fi

# if applicable, install also jQuery Tokeninput (for 'next' branch):
if grep -q install-jquery-tokeninput INSTALL; then
    sudo -u $CFG_INVENIO_USER make -s install-jquery-tokeninput
fi

# if applicable, install also Plupload (for 'next' branch):
if grep -q install-plupload-plugin INSTALL; then
    sudo -u $CFG_INVENIO_USER make -s install-plupload-plugin
fi

# if applicable, install also Hogan (for 'next' branch):
if grep -q install-hogan-plugin INSTALL; then
    sudo -u $CFG_INVENIO_USER make -s install-hogan-plugin
fi

# make special sudo powered place for LibreOffice:
sudo mkdir -p $CFG_INVENIO_PREFIX/var/tmp/ooffice-tmp-files
sudo chown -R nobody $CFG_INVENIO_PREFIX/var/tmp/ooffice-tmp-files
sudo chmod -R 755 $CFG_INVENIO_PREFIX/var/tmp/ooffice-tmp-files

# set up invenio-local.conf:
siteurl=${CFG_INVENIO_HOSTNAME}
if [ "${CFG_INVENIO_DOMAINNAME}" = "localhost" ] || [ "${CFG_INVENIO_DOMAINNAME}" = "localdomain" ]; then
    siteurl="localhost"
else
    siteurl=${siteurl}.${CFG_INVENIO_DOMAINNAME}
fi
sitesecureurl=${siteurl}
if [ "${CFG_INVENIO_PORT_HTTP}" != "80" ]; then
    siteurl=${siteurl}:${CFG_INVENIO_PORT_HTTP}
fi
if [ "${CFG_INVENIO_PORT_HTTPS}" != "443" ]; then
    sitesecureurl=${sitesecureurl}:${CFG_INVENIO_PORT_HTTPS}
fi
echo "[Invenio]
CFG_SITE_URL = http://${siteurl}
CFG_SITE_SECURE_URL = https://${sitesecureurl}
CFG_DATABASE_NAME = ${CFG_INVENIO_DATABASE_NAME}
CFG_DATABASE_USER = ${CFG_INVENIO_DATABASE_USER}
CFG_DATABASE_PASS = ${CFG_INVENIO_DATABASE_PASS}
CFG_SITE_ADMIN_EMAIL = ${CFG_INVENIO_ADMIN}
CFG_SITE_SUPPORT_EMAIL = ${CFG_INVENIO_ADMIN}
CFG_WEBALERT_ALERT_ENGINE_EMAIL = ${CFG_INVENIO_ADMIN}
CFG_WEBCOMMENT_ALERT_ENGINE_EMAIL = ${CFG_INVENIO_ADMIN}
CFG_WEBCOMMENT_DEFAULT_MODERATOR = ${CFG_INVENIO_ADMIN}
CFG_BIBAUTHORID_AUTHOR_TICKET_ADMIN_EMAIL = ${CFG_INVENIO_ADMIN}
CFG_BIBCATALOG_SYSTEM_EMAIL_ADDRESS = ${CFG_INVENIO_ADMIN}
CFG_BIBSCHED_PROCESS_USER = ${CFG_INVENIO_USER}" | \
    sudo -u $CFG_INVENIO_USER tee $CFG_INVENIO_PREFIX/etc/invenio-local.conf

# if applicable, append language option:
if [ "$CFG_INVENIO_SITE_LANGS" != "all" ]; then
    echo "CFG_SITE_LANGS = ${CFG_INVENIO_SITE_LANGS}" | \
    sudo -u $CFG_INVENIO_USER tee -a $CFG_INVENIO_PREFIX/etc/invenio-local.conf
fi

# if applicable, create secret key:
if grep -q create-secret-key INSTALL; then
    sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/inveniocfg --update-all
    sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/inveniocfg --create-secret-key
    # FIXME: the following line is a hack that was needed to overcome
    # certain virtualenv confusion at times.  The confusion was
    # leading to a situation where it was not possible to import
    # generated CFG_SITE_SECRET_KEY later; the system still saw the
    # old empty key value.  The line below deletes corresponding pyc
    # file which solves the problem in a workaround way until the
    # issue is fully debugged.  Ugly, but works, and does not harm
    # anything.
    sudo -u $CFG_INVENIO_USER rm -f $CFG_INVENIO_PREFIX/lib/python/invenio/config.pyc
fi

# update Invenio with this information:
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/inveniocfg --update-all

# MySQL-5.5 hack: before dropping and recreating tables, let's stop
# Apache and let's restart MySQL to free any DB connections we may
# have.  This helps in case we are running MySQL-5.5 where otherwise
# we could get into "Waiting for table metadata lock" situations due
# to other existing DB sessions.
sudo $CFG_INVENIO_APACHECTL stop
# NOTE: the following is no longer needed as of
# Invenio 7f63d3c31ce93aac83c5cf927d769f33fcc6c6d1
# sudo $CFG_INVENIO_MYSQLCTL restart

# MySQL-5.5 hack: also, let's drop tables here in the shell, rather
# than from within inveniocfg, where MySQLdb may open new sessions
# that may lead to autocommit and metadata lock issues.
$CFG_INVENIO_PREFIX/bin/dbexec < $CFG_INVENIO_PREFIX/lib/sql/invenio/tabdrop.sql

# drop and recreate tables and Atlantis demo site:
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/inveniocfg --create-tables --yes-i-know

# if needed, load BibField configuration (useful for `next' branch):
if grep -q load-bibfield-conf INSTALL; then
    sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/inveniocfg --load-bibfield-conf
fi

# update Apache configuration now: (this needs to be done after table
# creation in the next branch)
sudo -u $CFG_INVENIO_USER VIRTUAL_ENV=$VIRTUAL_ENV $CFG_INVENIO_PREFIX/bin/inveniocfg --create-apache-conf

# create demo site
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/inveniocfg --create-demo-site --yes-i-know

# MySQL-5.5 hack: restart Apache back:
sudo $CFG_INVENIO_APACHECTL start

# load Atlantis demo records:
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/inveniocfg --load-demo-records --yes-i-know

# restart Invenio WSGI app:
sudo -u $CFG_INVENIO_USER touch $CFG_INVENIO_PREFIX/var/www-wsgi/invenio.wsgi

echo "[INFO] Done."
