#!/bin/sh
#
# A helper devscript to recreate Invenio demo site.  Assumes an
# already running Invenio instance on the box, and certain sudo
# rights.  For more information, see
# <https://github.com/tiborsimko/invenio-devscripts>.
#
# Tibor Simko <tibor.simko@cern.ch>
#
# Copyright (C) 2011 CERN.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

# config section:
CFG_INVENIO_SRCDIR=${CFG_INVENIO_SRCDIR:=~/private/src/invenio}
CFG_INVENIO_PREFIX=${CFG_INVENIO_PREFIX:=/opt/invenio}
CFG_INVENIO_HOSTNAME=${CFG_INVENIO_HOSTNAME:=pcuds07}
CFG_INVENIO_DOMAINNAME=${CFG_INVENIO_DOMAINNAME:=cern.ch}
CFG_INVENIO_USER=${CFG_INVENIO_USER:=www-data}
CFG_INVENIO_ADMIN=${CFG_INVENIO_ADMIN:=tibor.simko@cern.ch}

# sanity check: CLI confirmation
if [ "$1" != "--yes-i-know" ]; then
    echo "[ERROR] You did not use --yes-i-know.  Not going to recreate Invenio demo site."
    exit
fi

# quit on errors and potentially unbound symbols:
set -o errexit
set -o nounset

# sanity check: hostname
if [ "`hostname`" != "$CFG_INVENIO_HOSTNAME" ]; then
    echo "[ERROR] This hostname is not whitelisted for recreating the demo site."
    exit
fi

# give user a chance to quit:
echo "[INFO] GOING TO RECREATE YOUR INVENIO DEMO SITE IN 5 SECONDS!"
echo -n "[INFO] THIS IS YOUR LAST CHANCE TO INTERRUPT BY PRESSING Ctrl-C! "
for i in 0 1 2 3 4; do
    echo -n "."
    sleep 1
done
echo

# wipe out existing installation place:
sudo rm -rf $CFG_INVENIO_PREFIX/var/tmp/ooffice-tmp-files
sudo -u $CFG_INVENIO_USER rm -rf $CFG_INVENIO_PREFIX/*

# install Invenio sources:
cd $CFG_INVENIO_SRCDIR
make -s
sudo -u $CFG_INVENIO_USER make -s install
sudo -u $CFG_INVENIO_USER make -s install-jquery-plugins
sudo -u $CFG_INVENIO_USER make -s install-mathjax-plugin
sudo -u $CFG_INVENIO_USER make -s install-fckeditor-plugin
sudo -u $CFG_INVENIO_USER make -s install-pdfa-helper-files

# make special sudo powered place for LibreOffice:
sudo mkdir -p $CFG_INVENIO_PREFIX/var/tmp/ooffice-tmp-files
sudo chown -R nobody $CFG_INVENIO_PREFIX/var/tmp/ooffice-tmp-files
sudo chmod -R 755 $CFG_INVENIO_PREFIX/var/tmp/ooffice-tmp-files

# set up invenio-local.conf:
echo "[Invenio]
CFG_SITE_URL = http://${CFG_INVENIO_HOSTNAME}.${CFG_INVENIO_DOMAINNAME}
CFG_SITE_SECURE_URL = https://${CFG_INVENIO_HOSTNAME}.${CFG_INVENIO_DOMAINNAME}
CFG_SITE_ADMIN_EMAIL = ${CFG_INVENIO_ADMIN}
CFG_SITE_SUPPORT_EMAIL = ${CFG_INVENIO_ADMIN}
CFG_WEBALERT_ALERT_ENGINE_EMAIL = ${CFG_INVENIO_ADMIN}
CFG_WEBCOMMENT_ALERT_ENGINE_EMAIL = ${CFG_INVENIO_ADMIN}
CFG_WEBCOMMENT_DEFAULT_MODERATOR = ${CFG_INVENIO_ADMIN}
CFG_BIBAUTHORID_AUTHOR_TICKET_ADMIN_EMAIL = ${CFG_INVENIO_ADMIN}" | \
    sudo -u $CFG_INVENIO_USER tee $CFG_INVENIO_PREFIX/etc/invenio-local.conf

# install Atlantis demo site with demo records:
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/inveniocfg --update-all \
                                                             --create-apache-conf \
                                                             --drop-demo-site \
                                                             --create-demo-site \
                                                             --load-demo-records \
                                                             --yes-i-know

# restart Invenio WSGI app:
sudo -u $CFG_INVENIO_USER touch $CFG_INVENIO_PREFIX/var/www-wsgi/invenio.wsgi

echo "[INFO] Done."
