#!/bin/sh
#
# A helper devscript to install (parts of) Invenio source tree
# followed by restarting WSGI application.  For more information, see
# <https://github.com/tiborsimko/invenio-devscripts>.
#
# Tibor Simko <tibor.simko@cern.ch>
#
# Copyright (C) 2011 CERN.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

# config section:
CFG_INVENIO_PREFIX=${CFG_INVENIO_PREFIX:=/opt/invenio}
CFG_INVENIO_USER=${CFG_INVENIO_USER:=www-data}

# quit on errors and potentially unbound symbols:
set -o errexit
set -o nounset

# install sources and restart WSGI application:
(make -s && sudo -u ${CFG_INVENIO_USER} make -s install && \
        sudo -u ${CFG_INVENIO_USER} ${CFG_INVENIO_PREFIX}/bin/inveniocfg --update-all && \
        sudo -u ${CFG_INVENIO_USER} touch ${CFG_INVENIO_PREFIX}/var/www-wsgi/invenio.wsgi) > /dev/null
echo "invenio-make-install finished."
