#!/bin/bash
#
# A helper devscript to kickstart Invenio development environment with
# an Invenio demo site on a fresh (virtual) machine in a fully
# automated, unassited way.  Tested mostly on Debian, Ubuntu,
# Scientific Linux, CentOS.  For more information, please see
# <https://github.com/tiborsimko/invenio-devscripts>.
#
# Tibor Simko <tibor.simko@cern.ch>
#
# Copyright (C) 2013 CERN.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

# config section:
export CFG_INVENIO_SRCDIR=${CFG_INVENIO_SRCDIR:=~/private/src/invenio}
export CFG_INVENIO_PORT_HTTP=${CFG_INVENIO_PORT_HTTP:=80}
export CFG_INVENIO_PORT_HTTPS=${CFG_INVENIO_PORT_HTTPS:=443}

# sanity check: CLI confirmation
if [ "$1" != "--yes-i-know" ]; then
    echo "[ERROR] You did not use --yes-i-know.  Not going to kickstart Invenio on this machine."
    exit 1
fi

if [ "$2" != "--yes-i-really-know" ]; then
    echo "[ERROR] You did not use --yes-i-really-know.  Not going to kickstart Invenio on this machine."
    exit 1
fi

# quit on errors and potentially unbound symbols:
set -o errexit
set -o nounset

# give user a chance to quit:
echo "[INFO] DANGER, DANGER! KICK-STARTING THIS BOX IN 5 SECONDS!"
echo -n "[INFO] THIS IS YOUR LAST CHANCE TO INTERRUPT BY PRESSING Ctrl-C! "
for i in 0 1 2 3 4; do
    echo -n "."
    sleep 1
done
echo

# does the box have git?
if [ ! -e /usr/bin/git ] && [ ! -e /usr/local/bin/git ] ; then
    echo "[ERROR] Cannot find git.  Please install it."
    echo "[ERROR] Example: sudo apt-get install -y git."
    exit 1
fi

# clone devscripts:
mkdir -p $(dirname ${CFG_INVENIO_SRCDIR})
cd $(dirname ${CFG_INVENIO_SRCDIR})
if [ -d invenio-devscripts/.git ]; then
    echo "[INFO] invenio-devscripts sources seem to be already installed."
else
    git clone https://github.com/tiborsimko/invenio-devscripts.git
fi
if [ -d invenio/.git ]; then
    echo "[INFO] invenio sources seem to be already installed."
else
    git clone https://github.com/inveniosoftware/invenio.git

    # Now, if we are using Python-2.4 only, i.e. on RHEL5 like systems,
    # then force Invenio/maint-1.1 since Invenio/master requires
    # Python-2.6 minimally:
    if [ -e /etc/redhat-release ]; then
        if grep -q ' 5.' /etc/redhat-release; then
            (cd invenio && git checkout maint-1.1)
        fi
    fi
fi

# set up env/opt/home development environment:
${CFG_INVENIO_SRCDIR}-devscripts/invenio-setup-environment --yes-i-know

# Now we have to reread CFG_INVENIO_* variables set up in the previous
# step.  Let's use eval here, since e.g. on Ubuntu vagrant box,
# with default settings, non-interactive reloading of ~/.bashrc is
# forbidden
eval $(grep "export CFG_INVENIO" $HOME/.bashrc)
eval $(grep "export PATH=" $HOME/.bashrc)

# install Apache/MySQL/Python/etc prerequisites:
${CFG_INVENIO_SRCDIR}-devscripts/invenio-setup-prerequisites --yes-i-know

# install Invenio demo site instance:
${CFG_INVENIO_SRCDIR}-devscripts/invenio-recreate-demo-site --yes-i-know

# end of file
