#!/bin/sh
#
# A helper devscript to run code kwalitee checks.  This is mostly a
# convenience wrapper around kwalitee.py.  For more information, see
# <https://github.com/tiborsimko/invenio-devscripts>.
#
# Tibor Simko <tibor.simko@cern.ch>
#
# Copyright (C) 2011 CERN.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

# config section:
CFG_INVENIO_SRCDIR=${CFG_INVENIO_SRCDIR:=~/private/src/invenio}

# quit on errors and potentially unbound symbols:
set -o errexit
set -o nounset

# run code kwalitee checks:
python ${CFG_INVENIO_SRCDIR}/modules/miscutil/lib/kwalitee.py $@
