#!/bin/sh
#
# Generates and publishes Invenio code browser pages.  Assumes having
# installed Invenio locally first.
#
# Tibor Simko <tibor.simko@cern.ch>
#
# Copyright (C) 2011 CERN
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

CODEBROWSERTMPDIR=/tmp/$(basename $0)-pages
CODEBROWSERTARGETDIR=simko@pcudssw1515.cern.ch:/opt/websites/invenio-software.org/htdocs/code-browser

ACTION=$1

# config section:
CFG_INVENIO_PREFIX=${CFG_INVENIO_PREFIX:=/opt/invenio}

usage () {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "   --help                         print this help"
    echo "   --check-docstrings             check overall docstrings compliance (rough only)"
    echo "   --generate-code-browser-pages  generate Invenio code browser pages (locally)"
    echo "   --publish-code-browser-pages   publish previsouly generated Invenio code browser pages (on the web)"
}

if [ "$ACTION" = "--help" ] || [ "$ACTION" = "-h" ]; then
    usage
elif [ "$ACTION" = "--check-docstrings" ]; then
    cd /tmp
    for afile in ${CFG_INVENIO_PREFIX}/lib/python/invenio/*.py; do
        epydoc $afile > /dev/null 2>&1
        if [ $? -ne 0 ]; then
            echo "[ERROR] Bad docstrings in ${afile}; won't be able to generate code browser pages."
        fi
    done
elif [ "$ACTION" = "--generate-code-browser-pages" ]; then
    echo "[INFO] Preparing ${CODEBROWSERTMPDIR}..."
    rm -rf $CODEBROWSERTMPDIR
    mkdir -p $CODEBROWSERTMPDIR
    echo "[INFO] Launching epydoc..."
    epydoc --verbose \
        --name="Invenio" \
        --url="http://invenio-software.org/" \
        --exclude='refextract' \
        --output=$CODEBROWSERTMPDIR \
        --debug \
        invenio
    cp -a $CODEBROWSERTMPDIR/frames.html $CODEBROWSERTMPDIR/index.html
    echo "[INFO] Code browser pages are generated.  Check them out in your browser via:"
    echo "[INFO]   conkeror file://${CODEBROWSERTMPDIR}/frames.html"
    echo "[INFO] If OK, then publish these pages via $0 --publish-code-browser-pages."
elif [ "$ACTION" = "--publish-code-browser-pages" ]; then
    echo "[INFO] Copying files onto ${CODEBROWSERTARGETDIR}..."
    rsync -rlptDvz -e ssh \
        --exclude '*~' \
        --exclude 'Publish*' \
        --delete \
        ${CODEBROWSERTMPDIR}/ ${CODEBROWSERTARGETDIR}
    echo "[INFO] Code browser pages have been published."
else
    echo "[ERROR] Please specify appropriate CLI option."
    usage
    exit 1
fi
